export const courseScheduleData = [
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 110,
      Section: 'A01',
      Title: 'FUNDAMENTAL PROGRAMING:I',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1000,
      End: 1120,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 8,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 110,
      Section: 'A02',
      Title: 'FUNDAMENTAL PROGRAMING:I',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1000,
      End: 1120,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 70,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 115,
      Section: 'A01',
      Title: 'FUNDAMENTAL PROGRAMING:II',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 8,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 115,
      Section: 'A02',
      Title: 'FUNDAMENTAL PROGRAMING:II',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 70,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 225,
      Section: 'A01',
      Title: 'ALGORITHMS+DATA STUCT:I',
      SchedType: 'LEC',
      Instructor: 'Jabbari, Hosna',
      Bldg: 'HSD',
      Room: 'A240',
      Begin: 930,
      End: 1020,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 55,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 225,
      Section: 'A02',
      Title: 'ALGORITHMS+DATA STUCT:I',
      SchedType: 'LEC',
      Instructor: 'Jabbari, Hosna',
      Bldg: 'HSD',
      Room: 'A240',
      Begin: 930,
      End: 1020,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 20,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 226,
      Section: 'A01',
      Title: 'ALGORITHMS+DATA STRUCTURE II',
      SchedType: 'LEC',
      Instructor: 'Yong, Quinton',
      Bldg: 'ECS',
      Room: '125',
      Begin: 1130,
      End: 1220,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 70,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 226,
      Section: 'A02',
      Title: 'ALGORITHMS+DATA STRUCTURE II',
      SchedType: 'LEC',
      Instructor: 'Yong, Quinton',
      Bldg: 'ECS',
      Room: '125',
      Begin: 1130,
      End: 1220,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 30,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 230,
      Section: 'A01',
      Title: 'COMPUTER ARCHITECTURE',
      SchedType: 'LEC',
      Instructor: 'Zastre, Michael',
      Bldg: 'ECS',
      Room: '116',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 55,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 230,
      Section: 'A02',
      Title: 'COMPUTER ARCHITECTURE',
      SchedType: 'LEC',
      Instructor: 'Zastre, Michael',
      Bldg: 'ECS',
      Room: '116',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 10,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 110,
      Section: 'A01',
      Title: 'FUNDAMENTAL PROGRAMING:I',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1000,
      End: 1120,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 8,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 110,
      Section: 'A02',
      Title: 'FUNDAMENTAL PROGRAMING:I',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1000,
      End: 1120,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 70,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 115,
      Section: 'A01',
      Title: 'FUNDAMENTAL PROGRAMING:II',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 8,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 115,
      Section: 'A02',
      Title: 'FUNDAMENTAL PROGRAMING:II',
      SchedType: 'LEC',
      Instructor: 'Berg, Celina',
      Bldg: 'ECS',
      Room: '123',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 70,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 225,
      Section: 'A01',
      Title: 'ALGORITHMS+DATA STUCT:I',
      SchedType: 'LEC',
      Instructor: 'Jabbari, Hosna',
      Bldg: 'HSD',
      Room: 'A240',
      Begin: 930,
      End: 1020,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 55,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 225,
      Section: 'A02',
      Title: 'ALGORITHMS+DATA STUCT:I',
      SchedType: 'LEC',
      Instructor: 'Jabbari, Hosna',
      Bldg: 'HSD',
      Room: 'A240',
      Begin: 930,
      End: 1020,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 20,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 226,
      Section: 'A01',
      Title: 'ALGORITHMS+DATA STRUCTURE II',
      SchedType: 'LEC',
      Instructor: 'Yong, Quinton',
      Bldg: 'ECS',
      Room: '125',
      Begin: 1130,
      End: 1220,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 70,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 226,
      Section: 'A02',
      Title: 'ALGORITHMS+DATA STRUCTURE II',
      SchedType: 'LEC',
      Instructor: 'Yong, Quinton',
      Bldg: 'ECS',
      Room: '125',
      Begin: 1130,
      End: 1220,
      Days: 'TWF',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 30,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 230,
      Section: 'A01',
      Title: 'COMPUTER ARCHITECTURE',
      SchedType: 'LEC',
      Instructor: 'Zastre, Michael',
      Bldg: 'ECS',
      Room: '116',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 55,
    },
    {
      Term: 202205,
      Subj: 'CSC',
      Num: 230,
      Section: 'A02',
      Title: 'COMPUTER ARCHITECTURE',
      SchedType: 'LEC',
      Instructor: 'Zastre, Michael',
      Bldg: 'ECS',
      Room: '116',
      Begin: 1300,
      End: 1420,
      Days: 'MR',
      StartDate: '04 May 2022',
      EndDate: '29 Jul 2022',
      Cap: 10,
    }
  ];